apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-delta
  namespace: nexus18-research
  labels:
    app: delta
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Gi
