apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexus-svc-account
  namespace: nexus18-research
rules:
  - apiGroups:
      - ""
      - "batch"
      - "extensions"
      - "apps"
      - "networking.k8s.io"
      - "policy"
    resources:
      - "*"
      - "ingresses"
    verbs: ["*"]
