apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexus-svc-account
  namespace: nexus18-research
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nexus-svc-account
subjects:
  - kind: ServiceAccount
    name: nexus-svc-account
    namespace: nexus18-research
