apiVersion: v1
kind: Service
metadata:
  name: blazegraph
  namespace: nexus18-research
  labels:
    app: blazegraph
    group: infra
spec:
  ports:
    - name: http
      port: 9999
  selector:
    app: blazegraph
    group: infra
  type: ClusterIP
  sessionAffinity: None
