apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: nexus18-research
spec:
  interval: 30m
  url: https://prometheus-community.github.io/helm-charts
